global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Autofac;
global using CarpeDiem.DataTools.Calculator;
global using CarpeDiem.DataTools.Calculator.Presenters;
global using CarpeDiem.DataTools.Calculator.Requests;
global using CarpeDiem.DataTools.Calculator.Views;
global using CarpeDiem.DataTools.Tasks;
global using CarpeDiem.DataTools.Tasks.Presenters;
global using CarpeDiem.DataTools.Workbench;
global using CarpeDiem.DataTools.Workbench.Events;
global using CarpeDiem.DataTools.Workbench.Presenters;
global using NSubstitute;
global using Xunit;
global using static NSubstitute.Substitute;
global using static Xunit.Assert;